version: '3.8'

# Legacy database-only compose file
# For full stack deployment, use ../docker-compose.yml instead

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_math_helper_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_math_helper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mathpassword
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_math_helper"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: