version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai_math_helper_db
    environment:
      - POSTGRES_PASSWORD=mathpassword
      - POSTGRES_DB=ai_math_helper
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: