import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'data.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'data.g.dart';

@freezed
abstract class MainData with _$MainData {
  const factory MainData({required int count}) = _MainData;

  factory MainData.fromJson(Map<String, Object?> json) =>
      _$MainDataFromJson(json);
}
