// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYZk9_BhpcuBIeYgM3QpllPU1kmg2m-M',
    appId: '1:752221570574:web:f1c63ab050d091ea27de5f',
    messagingSenderId: '752221570574',
    projectId: 'koreisai-cms',
    authDomain: 'koreisai-cms.firebaseapp.com',
    storageBucket: 'koreisai-cms.firebasestorage.app',
    measurementId: 'G-27JYE7EBGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-W1k2o4WWiY5pleKZtlcb6cluRoxC_c',
    appId: '1:752221570574:android:81e495392a3117db27de5f',
    messagingSenderId: '752221570574',
    projectId: 'koreisai-cms',
    storageBucket: 'koreisai-cms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyiRFjh5fDQG31zPsrltxCo4BcNTG1gAU',
    appId: '1:752221570574:ios:8ae3b5d165a3e15a27de5f',
    messagingSenderId: '752221570574',
    projectId: 'koreisai-cms',
    storageBucket: 'koreisai-cms.firebasestorage.app',
    androidClientId: '752221570574-fgu95qk2pd1enr1uib12ma0o6h43tmka.apps.googleusercontent.com',
    iosClientId: '752221570574-k58gmaiop2ho846tmlcbgivcmhvh38nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiMathHelper',
  );

}